### ISSUE TITLE
Request Approval to Publish Privileged User guidance material

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#137]
Hello @cybersquirrel 

Please may I request approval to publish the Privileged User guidance material? The four documents are available in preview as follows:

- [Privileged User Guide](https://github.com/ministryofjustice/security-guidance/blob/priv0318/docs/privileged-user-guide.md)
- [Privileged User Backups, Removable Media and Incident Management Guide](https://github.com/ministryofjustice/security-guidance/blob/priv0318/docs/privileged-user-backups-removable-media-and-incident-management-guide.md)
- [Privileged User Configuration, Patching and Change Management Guide](https://github.com/ministryofjustice/security-guidance/blob/priv0318/docs/privileged-user-configuration-patching-and-change-management-guide.md)
- [Privileged User Logging and Protective Monitoring Guide](https://github.com/ministryofjustice/security-guidance/blob/priv0318/docs/privileged-user-logging-and-protective-monitoring-guide.md)

Many thanks.

**Comment by cybersquirrel** [comment]
Hello,

Thanks for sharing this, and the hard work on it all.

A few comments:

**Privileged User Guide**
- We are linking to a template IRAR rather than a process for how IRARs are generated (and by whom). That doesn't seem right (plus, the template is open to the internet, yet has an OFFICIAL SENSITIVE classification banner; presumably as a 'once completed, this is OFFICIAL SENSITIVE' but it gives a poor impression). 
- the resource monitoring section is very infrastructure (and indeed, on-prem infrastructure)-centric. I think we could thin this out a bit, as fewer and fewer PUs are going to have access to info like this as we migrate further to the cloud and up the *-aaS stacks.
- the WiFi point at the end doesn't make sense given the requirement to use the VPN.  

**Privileged User Backups, Removable Media and Incident Management Guide**
- The removable media section is a little vague as to whether PUs should do these things (e.g. sheep-dip media) or should enforce their users to do these things.
- bullet that starts "If privileged users identify a suspected or ..." - this feels like a restatement of the general 'what to do if there's an incident' guidance, but with other steps added? Have OST commented on this?

**general**
- on all of these, the text at the end about who to contact appears different to other content we have live?

Bet wishes,

Jon.

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel 

Many thanks for the feedback. We've updated the draft content accordingly; the updated preview can be see at the same links as before.

Please may I request approval to publish?

Many thanks.

**Comment by warmanaMOJ** [comment]
Hello @L-Crosby 

Please may we request approval to publish this guidance (not policy material).

Thank you.

**Comment by L-Crosby** [comment]
Reviewing now 

- Where we reference JML which seems a key point in the main guidance, can we link to the policy? 
- In 'Privileged User Backups, Removable Media and Incident Management Guide' - do we need to be stronger in telling people to avoid using removable media?

**Comment by L-Crosby** [comment]
Generally we might need to think about IRAR. We make a lot of reference to them in guidance bu I do not think many services actually have them. A wider discussion needed on this.

**Comment by L-Crosby** [comment]
Are people aware 'MoJ timing source' would it benefit from a link?

**Comment by L-Crosby** [comment]
Approved - none of my comments stop this from going live. Thanks all

**Comment by warmanaMOJ** [comment]
Thank you, content now published.

We've recorded the additional comments, and they are captured in a fresh task card for the backlog.
