### ISSUE TITLE
Does vulnerability-disclosure-security.txt need an update?

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/security-guidance#194]
Our service (Apply in the LAA) links to your vulnerability-disclosure-security.txt and we have received a notification from the NCSC's Active Cyber Defence Hub saying that the security 
> Please update your security.txt file to include mandatory fields.

With a link to https://securitytxt.org/, this states that the two required fields are
* Contact Required
* Expires Required Only 1 allowed

Do you often review and/or update your expiry dates?

**Comment by warmanaMOJ** [comment]
Hello @colinbruce 

I've checked the contents of the file; you are correct, the expiry date in the correct format was missing. I've fixed that now (to the end of the year). We normally review all content on a yearly basis - in practice reviews take place more often than that as part of content updates.

Regarding the contact details, I think it's sufficient for us to have a [URI](https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12#section-3.5.3), rather than a specific mail to address. The URI (to HackerOne) is already in place.

I hope these answers are helpful and satisfactory.

**Comment by colinbruce** [comment]
Awesome, thanks @warmana 👍

**Comment by colinbruce** [comment]
NCSC update regarding the missing `Expires` value :+1:
![image](https://user-images.githubusercontent.com/6757677/127303665-2b571e3b-0e23-4de1-80a0-3c96cb57c782.png)

**Comment by warmanaMOJ** [comment]
Thank you @colinbruce 👍🏻
