### ISSUE TITLE
Request approval to publish 'General advice on taking equipment abroad'

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#96]
@cybersquirrel Please may I request approval to publish the document [General advice on taking equipment abroad](https://github.com/ministryofjustice/security-guidance/blob/Migrate0814/docs/general-advice-on-taking-equipment-abroad.md)?

This is a document that was previously published on the Intranet, and is referred to by the recently-published [Accessing MOJ IT Systems From Abroad](https://github.com/ministryofjustice/security-guidance/blob/Migrate0814/docs/accessing-moj-it-systems-from-abroad.md).

**Comment by cybersquirrel** [comment]
Happy to approve this.

The only thing I thought might want tweaking is the "keep password + PINs separate" because if you're crossing a border with them written down / stored anywhere, then they're not separate (even if one is in your pocket and your device is in your backpack). But that's a tweak for the future, not a blocker to publishing.

**Comment by warmanaMOJ** [comment]
Thank you very much.
